services:
  # Full Stack Service (Backend + Frontend)
  - type: web
    name: land-cover-fullstack
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip && 
      pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt &&
      cd frontend && npm install && npm run build && cd ..
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GEE_PROJECT_ID
        value: gleaming-tube-445109-t2
      - key: GEE_CREDENTIALS
        sync: false
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    
  # Frontend Service (Static Site)
  - type: web
    name: land-cover-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
